name: model_training_pipeline

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every monday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install dependencies if a requirements file exists

      - name: Train model on new data
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
        run: python -m pipelines.model_training_pipeline